<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>DxCanvasProbe2</RootNamespace>
    <StartupObject>DxCanvasProbe2.Program</StartupObject>
    <UseWindowsForms>true</UseWindowsForms>
    <MyType>WindowsForms</MyType>
    <OptionStrict>On</OptionStrict>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DxCanvas\DxCanvas.vbproj" />
  </ItemGroup>

</Project>
