Imports System.Drawing
Imports Microsoft.VisualBasic.Imaging
Imports Microsoft.VisualBasic.Imaging.Drawing2D.Colors
Imports Brush = Microsoft.VisualBasic.Imaging.Brush
Imports SolidBrush = Microsoft.VisualBasic.Imaging.SolidBrush

Namespace Scene3D

    ''' <summary>
    ''' A small cache of the heat map color tables and the point brush tables.
    ''' </summary>
    ''' <remarks>
    ''' The color table of a scheme is generated by the color designer and is
    ''' cached here because the sampling of the scheme is relative expensive
    ''' while the rendered frame only needs another index of the very same
    ''' table. The embedded point colors that come from the source file are
    ''' cached as well.
    ''' </remarks>
    Public NotInheritable Class SceneColorPalette

        ''' <summary>
        ''' the number of sampled colors of a heat map scheme
        ''' </summary>
        Public Const Levels As Integer = 256

        Private ReadOnly embedded As New Dictionary(Of String, Brush)()
        Private m_table As Color()
        Private m_brushes As Brush()
        Private m_scheme As String = Nothing
        Private m_alpha As Integer = -1

        ''' <summary>
        ''' get the color table of the given heat map scheme
        ''' </summary>
        ''' <param name="scheme">the scheme name that the color designer understands</param>
        ''' <param name="alpha">the alpha channel of the generated colors</param>
        Public Function GetTable(scheme As String, alpha As Integer) As Color()
            If m_table Is Nothing OrElse m_scheme <> scheme OrElse m_alpha <> alpha Then
                m_scheme = scheme
                m_alpha = alpha

                Try
                    m_table = Designer.GetColors(scheme, Levels, alpha)
                Catch ex As Exception
                    ' an unknown scheme must not break the rendering frame
                    m_table = Nothing
                End Try

                If m_table Is Nothing OrElse m_table.Length = 0 Then
                    m_table = New Color() {Color.Gray}
                End If

                m_brushes = m_table _
                    .Select(Function(c As Color) DirectCast(New SolidBrush(c), Brush)) _
                    .ToArray()
            End If

            Return m_table
        End Function

        ''' <summary>
        ''' get the point brushes of the given heat map scheme, index zero is the
        ''' coldest color and the last index is the hottest color
        ''' </summary>
        Public Function GetBrushes(scheme As String, alpha As Integer) As Brush()
            Call GetTable(scheme, alpha)
            Return m_brushes
        End Function

        ''' <summary>
        ''' map a normalized value in [0, 1] onto the heat map of the given scheme
        ''' </summary>
        Public Function GetHeatBrush(t As Double, scheme As String, alpha As Integer) As Brush
            Dim table As Brush() = GetBrushes(scheme, alpha)
            Dim n As Integer = table.Length

            If t < 0 Then
                t = 0
            ElseIf t > 1 Then
                t = 1
            End If

            Dim index As Integer = CInt(t * (n - 1))

            If index < 0 Then
                index = 0
            ElseIf index > n - 1 Then
                index = n - 1
            End If

            Return table(index)
        End Function

        ''' <summary>
        ''' get the brush of a per point color that is stored as an html color
        ''' string, the brush is created once and reused afterwards
        ''' </summary>
        Public Function GetEmbeddedBrush(htmlColor As String) As Brush
            If String.IsNullOrEmpty(htmlColor) Then
                Return Nothing
            End If

            Dim brush As Brush = Nothing

            If embedded.TryGetValue(htmlColor, brush) Then
                Return brush
            Else
                Dim color As Color = htmlColor.TranslateColor(throwEx:=False)
                brush = New SolidBrush(color)
                SyncLock embedded
                    embedded(htmlColor) = brush
                End SyncLock
            End If

            Return brush
        End Function

        ''' <summary>
        ''' drop all of the cached tables and brushes
        ''' </summary>
        Public Sub Clear()
            embedded.Clear()
            m_table = Nothing
            m_brushes = Nothing
            m_scheme = Nothing
            m_alpha = -1
        End Sub

        ''' <summary>
        ''' the number of the cached per point colors
        ''' </summary>
        Public ReadOnly Property EmbeddedColorCount As Integer
            Get
                Return embedded.Count
            End Get
        End Property
    End Class
End Namespace
