'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System.Reflection

Namespace RoyT.TrueType.Properties


    ''' <summary>
    '''   A strongly-typed resource class, for looking up localized strings, etc.
    ''' </summary>
    ' This class was auto-generated by the StronglyTypedResourceBuilder
    ' class via a tool like ResGen or Visual Studio.
    ' To add or remove a member, edit your .ResX file then rerun ResGen
    ' with the /str option, or rebuild your VS project.
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")>
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
    Friend Class Resources

        Private Shared resourceMan As Global.System.Resources.ResourceManager

        Private Shared resourceCulture As Global.System.Globalization.CultureInfo

        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>
        Friend Sub New()
        End Sub

        ''' <summary>
        '''   Returns the cached ResourceManager instance used by this class.
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Friend Shared ReadOnly Property ResourceManager As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("RoyT.TrueType.Properties.Resources", GetType(Resources).GetTypeInfo().Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property

        ''' <summary>
        '''   Overrides the current thread's CurrentUICulture property for all
        '''   resource lookups using this strongly typed resource class.
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Friend Shared Property Culture As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set(value As Global.System.Globalization.CultureInfo)
                resourceCulture = value
            End Set
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to 0x0001 ar
        ''' 0x0002 bg
        ''' 0x0003 ca
        ''' 0x0004 zh-Hans
        ''' 0x0005 cs
        ''' 0x0006 da
        ''' 0x0007 de
        ''' 0x0008 el
        ''' 0x0009 en
        ''' 0x000A es
        ''' 0x000B fi
        ''' 0x000C fr
        ''' 0x000D he
        ''' 0x000E hu
        ''' 0x000F is
        ''' 0x0010 it
        ''' 0x0011 ja
        ''' 0x0012 ko
        ''' 0x0013 nl
        ''' 0x0014 no
        ''' 0x0015 pl
        ''' 0x0016 pt
        ''' 0x0017 rm
        ''' 0x0018 ro
        ''' 0x0019 ru
        ''' 0x001A bs
        ''' 0x001B sk
        ''' 0x001C sq
        ''' 0x001D sv
        ''' 0x001E th
        ''' 0x001F tr
        ''' 0x0020 ur
        ''' 0x0021 id
        ''' 0x0022 uk
        ''' 0x0023 be
        ''' 0x0024 sl
        ''' 0x0025 et
        ''' 0x0026 lv
        ''' 0x0027 lt
        ''' 0x0028 tg
        ''' 0x0029 fa
        ''' 0x002A vi
        ''' 0x002B hy
        ''' 0x002C az
        ''' 0x002D eu
        ''' 0x002E dsb
        ''' [rest of string was truncated]&quot;;.
        ''' </summary>
        Friend Shared ReadOnly Property LCIDMap As String
            Get
                Return ResourceManager.GetString("LCIDMap", resourceCulture)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized string similar to 0 en
        ''' 1 fr
        ''' 2 de
        ''' 3 it
        ''' 4 nl
        ''' 5 sv
        ''' 6 es
        ''' 7 da
        ''' 8 pt
        ''' 9 no
        ''' 10 he
        ''' 11 ja
        ''' 12 ar
        ''' 13 fi
        ''' 14 el
        ''' 15 is
        ''' 16 mt
        ''' 17 tr
        ''' 18 hr
        ''' 19 zh
        ''' 20 ur
        ''' 21 hi
        ''' 22 th
        ''' 23 ko
        ''' 24 lt
        ''' 25 pl
        ''' 26 hu
        ''' 27 et
        ''' 28 lv
        ''' 30 fo
        ''' 31 fa
        ''' 32 ru
        ''' 33 zh
        ''' 35 ga
        ''' 36 sq
        ''' 37 ro
        ''' 38 cs
        ''' 39 sk
        ''' 40 sl
        ''' 41 yi
        ''' 42 sr
        ''' 43 mk
        ''' 44 bg
        ''' 45 uk
        ''' 46 be
        ''' 47 uz
        ''' 48 kk
        ''' 49 az
        ''' 50 az
        ''' 51 hy
        ''' 52 ka
        ''' 53 mo
        ''' 54 ky
        ''' 55 tg
        ''' 56 tk
        ''' 57 mn
        ''' 58 mn
        ''' 59 ps
        ''' 60 ku
        ''' 61 ks
        ''' 62 sd
        ''' 63 bo
        ''' 64 ne
        ''' 65 sa
        ''' 66 mr
        ''' 67 bn
        ''' 68 as
        ''' 69 gu
        ''' 70 pa
        ''' 71 or
        ''' 72 ml
        ''' 73 kn
        ''' 74 ta
        ''' 75 te
        ''' 76 s [rest of string was truncated]&quot;;.
        ''' </summary>
        Friend Shared ReadOnly Property MacLanguageCodeMap As String
            Get
                Return ResourceManager.GetString("MacLanguageCodeMap", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
