'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Microsoft.VisualBasic.Drawing.Fonts.TrueType.Properties
    
    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  一个强类型的资源类，用于查找本地化的字符串等。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Resources
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  返回此类使用的缓存的 ResourceManager 实例。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Microsoft.VisualBasic.Drawing.Fonts.TrueType.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  重写当前线程的 CurrentUICulture 属性，对
        '''  使用此强类型资源类的所有资源查找执行重写。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查找类似 0x0001 ar
        '''0x0002 bg
        '''0x0003 ca
        '''0x0004 zh-Hans
        '''0x0005 cs
        '''0x0006 da
        '''0x0007 de
        '''0x0008 el
        '''0x0009 en
        '''0x000A es
        '''0x000B fi
        '''0x000C fr
        '''0x000D he
        '''0x000E hu
        '''0x000F is
        '''0x0010 it
        '''0x0011 ja
        '''0x0012 ko
        '''0x0013 nl
        '''0x0014 no
        '''0x0015 pl
        '''0x0016 pt
        '''0x0017 rm
        '''0x0018 ro
        '''0x0019 ru
        '''0x001A bs
        '''0x001B sk
        '''0x001C sq
        '''0x001D sv
        '''0x001E th
        '''0x001F tr
        '''0x0020 ur
        '''0x0021 id
        '''0x0022 uk
        '''0x0023 be
        '''0x0024 sl
        '''0x0025 et
        '''0x0026 lv
        '''0x0027 lt
        '''0x0028 tg
        '''0x0029 fa
        '''0x002A vi
        '''0x002B hy
        '''0x002C az
        '''0x002D eu
        '''0x002E dsb
        '''0x002F mk
        '''0x0030 st
        '''0x0031 ts
        '''0x0032 tn
        '''0x0033 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property LCIDMap() As String
            Get
                Return ResourceManager.GetString("LCIDMap", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 0 en
        '''1 fr
        '''2 de
        '''3 it
        '''4 nl
        '''5 sv
        '''6 es
        '''7 da
        '''8 pt
        '''9 no
        '''10 he
        '''11 ja
        '''12 ar
        '''13 fi
        '''14 el
        '''15 is
        '''16 mt
        '''17 tr
        '''18 hr
        '''19 zh
        '''20 ur
        '''21 hi
        '''22 th
        '''23 ko
        '''24 lt
        '''25 pl
        '''26 hu
        '''27 et
        '''28 lv
        '''30 fo
        '''31 fa
        '''32 ru
        '''33 zh
        '''35 ga
        '''36 sq
        '''37 ro
        '''38 cs
        '''39 sk
        '''40 sl
        '''41 yi
        '''42 sr
        '''43 mk
        '''44 bg
        '''45 uk
        '''46 be
        '''47 uz
        '''48 kk
        '''49 az
        '''50 az
        '''51 hy
        '''52 ka
        '''53 mo
        '''54 ky
        '''55 tg
        '''56 tk
        '''57 mn
        '''58 mn
        '''59 ps
        '''60 ku
        '''61 ks
        '''62 sd
        '''63 bo
        '''64 ne
        '''65 sa
        '''66 mr
        '''67 bn
        '''68 as
        '''69 gu
        '''70 pa
        '''71 or
        '''72 ml
        '''73 kn
        '''74 ta
        '''75 te
        '''76 si
        '''77 my
        '''78 km
        '''79 lo
        '''80 vi
        '''81 id
        '''82 tl
        '''83 ms
        '''84 ms
        '''85 am
        '''86 ti
        '''87 om
        '''88 so
        ''' [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property MacLanguageCodeMap() As String
            Get
                Return ResourceManager.GetString("MacLanguageCodeMap", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
